# Generated by Django 5.2.2 on 2025-06-07 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastoverride',
            unique_together=set(),
        ),
    ]
